# This is an example nrwal config file

# Make sure you change this directory to wherever you put this folder.
equation_directory:
  /Users/gbuster/code/NRWAL/getting_started/

something:
  equations::model::random_equation

np_thing:
  np.exp(something) + np.min(something)

out:
  equations::model::cost + something + np_thing
