hydrogen_flow_kg_h:
  np.nanmax(hydrogen_kg, axis=0)
dist_to_h2_load_miles:
  dist_to_h2_load_km * 0.621371
opex_pipeline:
   6 * dist_to_h2_load_miles
capex_pipeline_linear:
  (6.2385 * hydrogen_flow_kg_h + 339713) * dist_to_h2_load_km
capex_pipeline_EOS_nonlinear:
  (-0.000003 * (hydrogen_flow_kg_h**2) + 8.315613 * hydrogen_flow_kg_h + 339712) * dist_to_h2_load_km