dist_to_h2_load_miles:
  dist_to_h2_load_km * 0.621371
opex_pipeline:
   6 * dist_to_h2_load_miles
capex_pipeline_linear:
  (6.2385 * h2_flow_kg_h + 339713) * dist_to_h2_load_km
capex_pipeline_EOS_nonlinear:
  (-0.020744 * (h2_flow_kg_h**2) + 710.144314 * h2_flow_kg_h + 212320.312500) * dist_to_h2_load_km