normal_capacity:
  np.array([0.00, 0.03, 0.05, 0.10, 0.15, 0.20, 0.25, 1.00])
capacity_curve_mw:
  normal_capacity * plant_capacity * electrolyzer_size_ratio
hydrogen_curve_kg_mwh:
  np.array([0, 0, 12.12121212, 20.28397566, 20.92050209, 20.92050209, 20.28397566, 17.27115717])
hydrogen_kg:
  np.interp(resource_profile, capacity_curve_kg, hydrogen_curve_kg_mwh)
hydrogen_annual_kg:
  np.nansum(hydrogen_kg, axis=0)
