hydrogen_production_kg_mwh:
  18.02
hourly_hydrogen_kg:
  hydrogen_production_kg_mwh * resource_capacity_profile_mw
max_hourly_hydrogen_kg:
  hydrogen_production_kg_mwh * electrolyzer_size_mw
hydrogen_kg:
  np.where(hourly_hydrogen_kg < max_hourly_hydrogen_kg, hourly_hydrogen_kg, max_hourly_hydrogen_kg)
hydrogen_annual_kg:
  np.nansum(hydrogen_kg, axis=0)
